# Generated by Django 6.0.5 on 2026-06-16 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
